server:
  port: 7903
spring:
  application:
    name: consumer-ribbon
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://peer1:7900/eureka/,http://peer2:6900/eureka/,http://peer3:5900/eureka/